openapi: 3.0.3

info:
  title: PA POS Microservice
  version: 1.0.0
  description: Public Administration POS of Multi-channel Project
  contact:
    name: Antonio Tarricone
    email: antonio.tarricone@pagopa.it

servers:
  - description: Development Test
    url: https://mil-d-apim.azure-api.net/mil-papos
    x-internal: true
  - description: User Acceptance Test
    url: https://mil-u-apim.azure-api.net/mil-papos
    x-internal: true

tags:
  - name: terminals
    description: Terminals management operation
  - name: transactions
    description: Transactions management operation
  - name: pa
    description: Operation which can be invoked by Public Administration (the payee) Portal
  - name: pos
    description: Operation which can be invoked by POS (through a back-end)
  - name: psp
    description: Operation which can be invoked by POS PSP

security:
  - bearerAuth: [ ]

paths:
  /terminals:
    post:
      operationId: createTerminal
      description: Creates a new terminal
      tags: [ terminals, psp ]
      parameters:
        - $ref: '#/components/parameters/RequestId'
      requestBody:
        $ref: '#/components/requestBodies/CreateOrUpdateTerminal'
      responses:
        "201":
          #description: Created
          $ref: '#/components/responses/CreateTerminal'
        "400":
          #description: Bad request
          $ref: '#/components/responses/Error'
        "401":
          #description: Access token is missing or invalid
          $ref: '#/components/responses/Error'
        "403":
          #description: Forbidden
          $ref: '#/components/responses/Error'
        "406":
          #description: Not acceptable. Did you require application/json?
          $ref: '#/components/responses/Error'
        "409":
          #description: Already exists
          $ref: '#/components/responses/Error'
        "415":
          #description: Unsupported media type. Did you provide application/json?
          $ref: '#/components/responses/Error'
        "429":
          #description: Too many requests
          $ref: '#/components/responses/Error'
        "500":
          #description: Server error
          $ref: '#/components/responses/Error'
        default:
          description: Unexpected error

  /terminals/bulkload:
    post:
      operationId: bulkLoadTerminals
      description: Allows the bulk loading of a set of terminals.
      tags: [ terminals, psp ]
      parameters:
        - $ref: '#/components/parameters/RequestId'
      requestBody:
        $ref: '#/components/requestBodies/BulkLoadTerminals'
      responses:
        "202":
          #description: Accepted
          $ref: '#/components/responses/BulkLoadTerminals'
        "400":
          #description: Bad request
          $ref: '#/components/responses/Error'
        "401":
          #description: Access token is missing or invalid
          $ref: '#/components/responses/Error'
        "403":
          #description: Forbidden
          $ref: '#/components/responses/Error'
        "406":
          #description: Not acceptable. Did you require application/json?
          $ref: '#/components/responses/Error'
        "409":
          #description: Already exists
          $ref: '#/components/responses/Error'
        "415":
          #description: Unsupported media type
          $ref: '#/components/responses/Error'
        "429":
          #description: Too many requests
          $ref: '#/components/responses/Error'
        "500":
          #description: Server error
          $ref: '#/components/responses/Error'
        default:
          description: Unexpected error

  /terminals/bulkload/{bulkLoadingId}:
    get:
      operationId: getBulkLoadingStatusFile
      description: Returns a file with the status of bulk loading operation
      tags: [ terminals, psp ]
      parameters:
        - $ref: '#/components/parameters/RequestId'
        - $ref: '#/components/parameters/BulkLoadingId'
      responses:
        "200":
          #description: Returns the report of bulk loading operation
          $ref: '#/components/responses/BulkLoadingReport'
        "202":
          #description: Bulk loading still in progress
          $ref: '#/components/responses/NoContent'
        "400":
          #description: Bad request
          $ref: '#/components/responses/Error'
        "401":
          #description: Access token is missing or invalid
          $ref: '#/components/responses/Error'
        "403":
          #description: Forbidden
          $ref: '#/components/responses/Error'
        "406":
          #description: Not acceptable
          $ref: '#/components/responses/Error'
        "429":
          #description: Too many request
          $ref: '#/components/responses/Error'
        "500":
          #description: Server error
          $ref: '#/components/responses/Error'
        default:
          description: Unexpected error

  /terminals/findByPayeeCode:
    get:
      operationId: getTerminalListByPayeeCode
      description: Returns a page of terminals
      tags: [ terminals, pa ]
      parameters:
        - $ref: '#/components/parameters/RequestId'
        - $ref: '#/components/parameters/PayeeCode'
        - $ref: '#/components/parameters/PageNumber'
        - $ref: '#/components/parameters/PageSize'
      responses:
        "200":
          #description: Ok
          $ref: '#/components/responses/PageOfTerminalsWithWorkstations'
        "400":
          #description: Bad request
          $ref: '#/components/responses/Error'
        "401":
          #description: Access token is missing or invalid
          $ref: '#/components/responses/Error'
        "403":
          #description: Forbidden
          $ref: '#/components/responses/Error'
        "406":
          #description: Not acceptable. Did you require application/json?
          $ref: '#/components/responses/Error'
        "429":
          #description: Too many request
          $ref: '#/components/responses/Error'
        "500":
          #description: Server error
          $ref: '#/components/responses/Error'
        default:
          description: Unexpected error

  /terminals/findByPspId:
    get:
      operationId: getTerminalListByPspId
      description: Returns a page of terminals
      tags: [ terminals, psp ]
      parameters:
        - $ref: '#/components/parameters/RequestId'
        - $ref: '#/components/parameters/PspId'
        - $ref: '#/components/parameters/PageNumber'
        - $ref: '#/components/parameters/PageSize'
      responses:
        "200":
          #description: Ok
          $ref: '#/components/responses/PageOfTerminals'
        "400":
          #description: Bad request
          $ref: '#/components/responses/Error'
        "401":
          #description: Access token is missing or invalid
          $ref: '#/components/responses/Error'
        "403":
          #description: Forbidden
          $ref: '#/components/responses/Error'
        "406":
          #description: Not acceptable. Did you require application/json?
          $ref: '#/components/responses/Error'
        "429":
          #description: Too many request
          $ref: '#/components/responses/Error'
        "500":
          #description: Server error
          $ref: '#/components/responses/Error'
        default:
          description: Unexpected error

  /terminals/findByWorkstation:
    get:
      operationId: findTerminalsByWorkstation
      description: Returns the list of terminals linked to a cash desk
      tags: [ terminals, pa ]
      parameters:
        - $ref: '#/components/parameters/RequestId'
        - $ref: '#/components/parameters/PayeeCode'
        - $ref: '#/components/parameters/Workstation'
      responses:
        "200":
          #description: Ok
          $ref: '#/components/responses/TerminalsWithWorkstations'
        "400":
          #description: Bad request 
          $ref: '#/components/responses/Error'
        "401":
          #description: Access token is missing or invalid
          $ref: '#/components/responses/Error'
        "403":
          #description: Forbidden
          $ref: '#/components/responses/Error'
        "406":
          #description: Not acceptable. Did you require application/json?
          $ref: '#/components/responses/Error'
        "429":
          #description: Too many request
          $ref: '#/components/responses/Error'
        "500":
          #description: Server error
          $ref: '#/components/responses/Error'
        default:
          description: Unexpected error

  /terminals/{terminalUuid}/updateWorkstations:
    patch:
      operationId: updateWorkstations
      description: Updates the list of cash desks linked to the terminal
      tags: [ terminals, pa ]
      parameters:
        - $ref: '#/components/parameters/RequestId'
        - $ref: '#/components/parameters/TerminalUuid'
      requestBody:
        $ref: '#/components/requestBodies/UpdateWorkstations'
      responses:
        "204":
          #description: No content
          $ref: '#/components/responses/NoContent'
        "400":
          #description: Bad request
          $ref: '#/components/responses/Error'
        "401":
          #description: Access token is missing or invalid
          $ref: '#/components/responses/Error'
        "403":
          #description: Forbidden
          $ref: '#/components/responses/Error'
        "404":
          #description: Not found
          $ref: '#/components/responses/Error'
        "406":
          #description: Not acceptable. Did you require application/json?
          $ref: '#/components/responses/Error'
        "415":
          #description: Unsupported media type. Did you provide application/json?
          $ref: '#/components/responses/Error'
        "429":
          #description: Too many requests
          $ref: '#/components/responses/Error'
        "500":
          #description: Server error
          $ref: '#/components/responses/Error'
        default:
          description: Unexpected error

  /terminals/{terminalUuid}:
    parameters:
      - $ref: '#/components/parameters/RequestId'
      - $ref: '#/components/parameters/TerminalUuid'

    patch:
      operationId: updateTerminal
      description: Updated terminal without modify linked cash desks
      tags: [ terminals, psp ]
      requestBody:
        $ref: '#/components/requestBodies/CreateOrUpdateTerminal'
      responses:
        "204":
          #description: No content
          $ref: '#/components/responses/NoContent'
        "400":
          #description: Bad request
          $ref: '#/components/responses/Error'
        "401":
          #description: Access token is missing or invalid
          $ref: '#/components/responses/Error'
        "403":
          #description: Forbidden
          $ref: '#/components/responses/Error'
        "404":
          #description: Not found
          $ref: '#/components/responses/Error'
        "406":
          #description: Not acceptable. Did you require application/json?
          $ref: '#/components/responses/Error'
        "415":
          #description: Unsupported media type. Did you provide application/json?
          $ref: '#/components/responses/Error'
        "429":
          #description: Too many requests
          $ref: '#/components/responses/Error'
        "500":
          #description: Server error
          $ref: '#/components/responses/Error'
        default:
          description: Unexpected error

    delete:
      operationId: deleteTerminal
      description: Deletes a terminal
      tags: [ terminals, psp ]
      responses:
        "204":
          #description: No content
          $ref: '#/components/responses/NoContent'
        "400":
          #description: Bad request
          $ref: '#/components/responses/Error'
        "401":
          #description: Access token is missing or invalid
          $ref: '#/components/responses/Error'
        "403":
          #description: Forbidden
          $ref: '#/components/responses/Error'
        "404":
          #description: Not found
          $ref: '#/components/responses/Error'
        "406":
          #description: Not acceptable. Did you require application/json?
          $ref: '#/components/responses/Error'
        "429":
          #description: Too many requests
          $ref: '#/components/responses/Error'
        "500":
          #description: Server error
          $ref: '#/components/responses/Error'
        default:
          description: Unexpected error

  /transactions:
    post:
      operationId: create
      summary: Creates a transaction
      description: Create a transaction from Public Administration (the payee) Portal
      tags: [ transactions, pa ]
      parameters:
        - $ref: '#/components/parameters/RequestId'
      requestBody:
        $ref: '#/components/requestBodies/CreateTransaction'
      responses:
        "204":
          #description: No content
          $ref: '#/components/responses/CreateTransaction'
        "400":
          #description: Bad request
          $ref: '#/components/responses/Error'
        "401":
          #description: Access token is missing or invalid
          $ref: '#/components/responses/Error'
        "403":
          #description: Forbidden
          $ref: '#/components/responses/Error'
        "406":
          #description: Not acceptable. Did you require application/json?
          $ref: '#/components/responses/Error'
        "415":
          #description: Unsupported media type. Did you provide application/json?
          $ref: '#/components/responses/Error'
        "429":
          #description: Too many request
          $ref: '#/components/responses/Error'
        "500":
          #description: Server error
          $ref: '#/components/responses/Error'
        default:
          description: Unexpected error

  /transactions/findByPayeeCode:
    get:
      operationId: getTransactionsByPayeeCode
      summary: Retrieves the list of transactions
      description: Retrieves the list of transactions by payee
      tags: [ transactions, pa ]
      parameters:
        - $ref: '#/components/parameters/RequestId'
        - $ref: '#/components/parameters/PayeeCode'
        - $ref: '#/components/parameters/StartDate'
        - $ref: '#/components/parameters/EndDate'
        - $ref: '#/components/parameters/SortStrategy'
        - $ref: '#/components/parameters/PageNumber'
        - $ref: '#/components/parameters/PageSize'
      responses:
        "200":
          #description: Found
          $ref: '#/components/responses/PageOfTransactions'
        "400":
          #description: Bad request
          $ref: '#/components/responses/Error'
        "401":
          #description: Access token is missing or invalid
          $ref: '#/components/responses/Error'
        "403":
          #description: Forbidden
          $ref: '#/components/responses/Error'
        "406":
          #description: Not acceptable. Did you require application/json?
          $ref: '#/components/responses/Error'
        "429":
          #description: Too many request
          $ref: '#/components/responses/Error'
        "500":
          #description: Server error
          $ref: '#/components/responses/Error'
        default:
          description: Unexpected error

  /transactions/findByPspId:
    get:
      operationId: getTransactionsByPspId
      summary: Retrieves the list of transactions
      description: Retrieves the list of transactions by PSP
      tags: [ transactions, psp ]
      parameters:
        - $ref: '#/components/parameters/RequestId'
        - $ref: '#/components/parameters/PspId'
        - $ref: '#/components/parameters/StartDate'
        - $ref: '#/components/parameters/EndDate'
        - $ref: '#/components/parameters/SortStrategy'
        - $ref: '#/components/parameters/PageNumber'
        - $ref: '#/components/parameters/PageSize'
      responses:
        "200":
          #description: Found
          $ref: '#/components/responses/PageOfTransactions'
        "400":
          #description: Bad request
          $ref: '#/components/responses/Error'
        "401":
          #description: Access token is missing or invalid
          $ref: '#/components/responses/Error'
        "403":
          #description: Forbidden
          $ref: '#/components/responses/Error'
        "406":
          #description: Not acceptable. Did you require application/json?
          $ref: '#/components/responses/Error'
        "429":
          #description: Too many request
          $ref: '#/components/responses/Error'
        "500":
          #description: Server error
          $ref: '#/components/responses/Error'
        default:
          description: Unexpected error

  /transactions/{transactionId}:
    parameters:
      - $ref: '#/components/parameters/RequestId'
      - $ref: '#/components/parameters/TransactionId'

    delete:
      operationId: deleteTransaction
      summary: Deletes a transaction
      description: Allows a Public Administration (the payee) Portal to delete a transaction
      tags: [ transactions, pa ]
      responses:
        "204":
          #description: No content
          $ref: '#/components/responses/NoContent'
        "400":
          #description: Bad request
          $ref: '#/components/responses/Error'
        "401":
          #description: Access token is missing or invalid
          $ref: '#/components/responses/Error'
        "403":
          #description: Forbidden
          $ref: '#/components/responses/Error'
        "404":
          #description: Not found
          $ref: '#/components/responses/Error'
        "406":
          #description: Not acceptable. Did you require application/json?
          $ref: '#/components/responses/Error'
        "429":
          #description: Too many requests
          $ref: '#/components/responses/Error'
        "500":
          #description: Server error
          $ref: '#/components/responses/Error'
        default:
          description: Unexpected error

    patch:
      operationId: updateTransaction
      description: Updates amount and status of a transaction
      tags: [ transactions, pa ]
      requestBody:
        $ref: '#/components/requestBodies/UpdateTransaction'
      responses:
        "204":
          #description: No content
          $ref: '#/components/responses/NoContent'
        "400":
          #description: Bad request
          $ref: '#/components/responses/Error'
        "401":
          #description: Access token is missing or invalid
          $ref: '#/components/responses/Error'
        "403":
          #description: Forbidden
          $ref: '#/components/responses/Error'
        "404":
          #description: Not found
          $ref: '#/components/responses/Error'
        "406":
          #description: Not acceptable. Did you require application/json?
          $ref: '#/components/responses/Error'
        "415":
          #description: Unsupported media type. Did you provide application/json?
          $ref: '#/components/responses/Error'
        "429":
          #description: Too many requests
          $ref: '#/components/responses/Error'
        "500":
          #description: Server error
          $ref: '#/components/responses/Error'
        default:
          description: Unexpected error

    get:
      operationId: getTransaction
      description: Returns transaction data
      tags: [ transactions, pa, psp ]
      responses:
        "200":
          #description: Ok
          $ref: '#/components/responses/Transaction'
        "400":
          #description: Bad request
          $ref: '#/components/responses/Error'
        "401":
          #description: Access token is missing or invalid
          $ref: '#/components/responses/Error'
        "403":
          #description: Forbidden
          $ref: '#/components/responses/Error'
        "404":
          #description: Not found
          $ref: '#/components/responses/Error'
        "406":
          #description: Not acceptable. Did you require application/json?
          $ref: '#/components/responses/Error'
        "429":
          #description: Too many requests
          $ref: '#/components/responses/Error'
        "500":
          #description: Server error
          $ref: '#/components/responses/Error'
        default:
          description: Unexpected error

  /transactions/latest:
    get:
      operationId: getLatestTransaction
      summary: Retrieves the latest transaction
      description: Retrieves the latest transaction by POS and status
      tags: [ transactions, pos ]
      parameters:
        - $ref: '#/components/parameters/RequestId'
        - $ref: '#/components/parameters/PspId'
        - $ref: '#/components/parameters/TerminalId'
        - $ref: '#/components/parameters/Status'
      responses:
        "200":
          #description: Found
          $ref: '#/components/responses/Transaction'
        "400":
          #description: Bad request
          $ref: '#/components/responses/Error'
        "401":
          #description: Access token is missing or invalid
          $ref: '#/components/responses/Error'
        "403":
          #description: Forbidden
          $ref: '#/components/responses/Error'
        "404":
          #description: Not found
          $ref: '#/components/responses/Error'
        "406":
          #description: Not acceptable. Did you require application/json?
          $ref: '#/components/responses/Error'
        "429":
          #description: Too many request
          $ref: '#/components/responses/Error'
        "500":
          #description: Server error
          $ref: '#/components/responses/Error'
        default:
          description: Unexpected error

components:
  # ========================================================
  # Schemas
  # ========================================================
  schemas:
    # ------------------------------------------------------
    # Basic types
    # ------------------------------------------------------
    AccessControlAllowOrigin:
      description: Indicates whether the response can be shared with requesting code from the given origin
      type: string
      pattern: "^[ -~]{1,2048}$"
      minLength: 1
      maxLength: 2048

    BulkLoadingLocation:
      description: URL to get the status of bulk loading operation
      type: string
      format: uri
      pattern: "^[ -~]{1,2048}$"
      minLength: 1
      maxLength: 2048
      example: "https://mil-d-apim.azure-api.net/mil-papos/terminals/bulkload/4658fcb36e520a65b1be79d0"

    BulkLoadingId:
      description: ID of a bulk loading operation
      type: string
      pattern: "^[0-9a-f]{24}$"
      minLength: 24
      maxLength: 24
      example: "c7a1b24b0583477292ebdbaa"

    Enabled:
      description: True if the terminal is enabled
      type: boolean
      example: true

    ErrorCode:
      description: Error code
      type: string
      pattern: "^[A-F0-9]{9}$"
      minLength: 9
      maxLength: 9
      example: "001000005"

    ErrorDescription:
      description: Error description
      type: string
      pattern: "^[ -~]{1,256}$"
      minLength: 1
      maxLength: 256
      example: "Unexpected error from server"

    EuroCents:
      description: Amount in euro cents
      type: integer
      format: int64
      minimum: 1
      maximum: 99999999999
      example: 12345

    NoticeNumber:
      description: Notice number
      type: string
      pattern: "^[0-9]{18}$"
      minLength: 18
      maxLength: 18
      example: "485564829563528563"
    
    PageNumber:
      description: Number of the page
      type: integer
      format: int32
      minimum: 0
      maximum: 2147483647
      example: 1

    PageSize:
      description: Size of the page
      type: integer
      format: int32
      minimum: 1
      maximum: 128
      example: 20

    PayeeCode:
      description: Fiscal code of the subject that receives the payment
      type: string
      pattern: "^\\d{11}$"
      minLength: 11
      maxLength: 11
      example: "06534340721"

    PspId:
      description: ID of the POS service provider
      type: string
      pattern: "^[ -~]{1,64}$"
      minLength: 1
      maxLength: 64
      example: "AGID_01"

    RateLimitLimit:
      description: The number of allowed requests in the current period
      type: integer
      format: int32
      minimum: 1
      maximum: 240

    RateLimitReset:
      description: The number of seconds left in the current period
      type: integer
      format: int32
      minimum: 1
      maximum: 60

    RetryAfter:
      description: The number of seconds to wait before allowing a follow-up request
      type: integer
      format: int32
      minimum: 1
      maximum: 240
    
    Status:
      description: Status of the transaction
      type: string
      enum:
        - CLOSED_OK
        - ERROR_ON_PAYMENT
        - ABORT
        - CREATED
      example: "CLOSED_OK"
    
    TerminalId:
      description: ID of the terminal for the PSP
      type: string
      pattern: "^\\d{4,12}$"
      minLength: 4
      maxLength: 12
      example: "34523860"

    TerminalLocation:
      description: URL of the terminal
      type: string
      format: uri
      pattern: "^[ -~]{1,2048}$"
      minLength: 1
      maxLength: 2048
      example: "https://mil-d-apim.azure-api.net/mil-papos/terminals/c7a1b24b0583477292ebdbaa"

    TerminalUuid:
      description: UUID of a terminal for this layer
      type: string
      pattern: "^[0-9a-f]{24}$"
      minLength: 24
      maxLength: 24
      example: "c7a1b24b0583477292ebdbaa"

    Timestamp:
      description: Timestamp (ex. 2024-03-06T13:15:54Z, 2024-03-06T14:15:54+01:00)
      type: string
      format: date-time
      pattern: "^\\d{4}\\-\\d{2}\\-\\d{2}T\\d{2}:\\d{2}:\\d{2}(Z|(\\+|\\-)\\d{2}:\\d{2})$"
      minLength: 20
      maxLength: 25
      example: "2024-03-06T14:15:54+01:00"

    TransactionId:
      description: Transaction ID for this layer
      type: string
      pattern: "^[0-9a-f]{24}$"
      minLength: 24
      maxLength: 24
      example: "4658fcb36e520a65b1be79d0"

    TransactionLocation:
      description: URL of the transaction
      type: string
      format: uri
      pattern: "^[ -~]{1,2048}$"
      minLength: 1
      maxLength: 2048
      example: "https://mil-d-apim.azure-api.net/mil-papos/transactions/4658fcb36e520a65b1be79d0"

    UUID:
      description: UUID
      type: string
      pattern: "^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$"
      minLength: 36
      maxLength: 36
      example: "d0d654e6-97da-4848-b568-99fedccb642b"

    Workstation:
      description: Label indicating the cash desk that can use a terminal
      type: string
      pattern: "^[ -~]{1,64}$"
      minLength: 1
      maxLength: 64
      example: "cassa-1-ufficio-3"

    # ------------------------------------------------------
    # Complex types
    # ------------------------------------------------------
    CreateOrUpdateTerminal:
      description: Request to create or update a terminal by PSP
      type: object
      additionalProperties: false
      properties:
        pspId:
          $ref: '#/components/schemas/PspId'
        terminalId:
          $ref: '#/components/schemas/TerminalId'
        enabled:
          $ref: '#/components/schemas/Enabled'
        payeeCode:
          $ref: '#/components/schemas/PayeeCode'
      required:
        - pspId
        - terminalId
        - enabled
        - payeeCode
      example:
        pspId: "AGID_01"
        terminalId: "34523860"
        enabled: true
        payeeCode: "06534340721"

    CreateTransaction:
      description: Request to create a transaction from Public Administration (the payee) Portal
      type: object
      additionalProperties: false
      properties:
        pspId:
          $ref: '#/components/schemas/PspId'
        terminalId:
          $ref: '#/components/schemas/TerminalId'
        noticeNumber:
          $ref: '#/components/schemas/NoticeNumber'
        payeeCode:
          $ref: '#/components/schemas/PayeeCode'
      required:
        - pspId
        - terminalId
        - noticeNumber
        - payeeCode
      example:
        pspId: "AGID_01"
        terminalId: "34523860"
        noticeNumber: "485564829563528563"
        payeeCode: "06534340721"
    
    Error:
      description: Error details
      type: object
      additionalProperties: false
      properties:
        code:
          $ref: '#/components/schemas/ErrorCode'
        description:
          $ref: '#/components/schemas/ErrorDescription'
      required:
        - code
        - description
      example:
        code: "001000001"
        description: "Generic error"

    Errors:
      description: List of errors
      type: object
      additionalProperties: false
      properties:
        errors:
          type: array
          minItems: 1
          maxItems: 32
          items:
            $ref: '#/components/schemas/Error'
      required:
        - errors
      example:
        errors:
          - code: "00000000A"
            description: "Generic error"
          - code: "001000001"
            description: "Unexpected error from server"

    PageMetadata:
      description: Metadata of a page of data
      type: object
      additionalProperties: false
      properties:
        size:
          $ref: '#/components/schemas/PageSize'
        totalElements:
          description: Total number of items
          type: integer
          format: int32
          minimum: 0
          maximum: 2147483647
          example: 200
        totalPages:
          $ref: '#/components/schemas/PageNumber'
      example:
        size: 20
        totalElements: 100
        totalPages: 5

    PageOfTerminals:
      description: Page of terminals data
      allOf:
        - $ref: '#/components/schemas/Terminals'
        - type: object
          additionalProperties: false
          properties:
            page:
              $ref: '#/components/schemas/PageMetadata'
          required:
            - page
      example:
        terminals:
          - terminalUuid: "c7a1b24b0583477292ebdbaa"
            pspId: "AGID_01"
            terminalId: "34523860"
            enabled: true
            payeeCode: "06534340721"
          - terminalUuid: "635edc54ab35f303668bbe7e"
            pspId: "AGID_01"
            terminalId: "34523865"
            enabled: true
            payeeCode: "06534340721"
        page:
          size: 2
          totalElements: 5
          totalPages: 3

    PageOfTerminalsWithWorkstations:
      description: Page of terminals data
      allOf:
        - $ref: '#/components/schemas/TerminalsWithWorkstations'
        - type: object
          additionalProperties: false
          properties:
            page:
              $ref: '#/components/schemas/PageMetadata'
          required:
            - page
      example:
        terminals:
          - terminalUuid: "c7a1b24b0583477292ebdbaa"
            pspId: "AGID_01"
            terminalId: "34523860"
            enabled: true
            payeeCode: "06534340721"
            workstations:
              - "cassa-1-ufficio-3"
              - "cassa-2-ufficio-3"
          - terminalUuid: "635edc54ab35f303668bbe7e"
            pspId: "AGID_01"
            terminalId: "34523865"
            enabled: true
            payeeCode: "06534340721"
            workstations:
              - "cassa-3-ufficio-3"
              - "cassa-4-ufficio-3"
        page:
          size: 2
          totalElements: 5
          totalPages: 3

    PageOfTransactions:
      description: Page of transactions
      allOf:
        - type: object
          additionalProperties: false
          properties:
            transactions:
              $ref: '#/components/schemas/Transactions'
          required:
            - transactions
        - type: object
          additionalProperties: false
          properties:
            page:
              $ref: '#/components/schemas/PageMetadata'
          required:
            - page
      example:
        transactions:
          - id: "4658fcb36e520a65b1be79d0"
            pspId: "AGID_01"
            terminalId: "34523860"
            noticeNumber: "485564829563528563"
            payeeCode: "06534340721"
            creationTimestamp: "2024-03-06T13:15:54Z"
            lastUpdateTimestamp: "2024-03-06T13:16:33Z"
            status: "CLOSED_OK"
            amount: 12345
        page:
          size: 1
          totalElements: 5
          totalPages: 5

    Terminal:
      description: Data of a terminal
      type: object
      additionalProperties: false
      properties:
        terminalUuid:
          $ref: '#/components/schemas/TerminalUuid'
        pspId:
          $ref: '#/components/schemas/PspId'
        terminalId:
          $ref: '#/components/schemas/TerminalId'
        enabled:
          $ref: '#/components/schemas/Enabled'
        payeeCode:
          $ref: '#/components/schemas/PayeeCode'
      required:
        - terminalUuid
        - pspId
        - terminalId
        - enabled
        - payeeCode
      example:
        terminalUuid: "c7a1b24b0583477292ebdbaa"
        pspId: "AGID_01"
        terminalId: "34523860"
        enabled: true
        payeeCode: "06534340721"
    
    TerminalWithWorkstations:
      description: Data of a terminal
      type: object
      additionalProperties: false
      properties:
        terminalUuid:
          $ref: '#/components/schemas/TerminalUuid'
        pspId:
          $ref: '#/components/schemas/PspId'
        terminalId:
          $ref: '#/components/schemas/TerminalId'
        enabled:
          $ref: '#/components/schemas/Enabled'
        payeeCode:
          $ref: '#/components/schemas/PayeeCode'
        workstations:
          $ref: '#/components/schemas/WorkstationsArray'
      required:
        - terminalUuid
        - pspId
        - terminalId
        - enabled
        - payeeCode
        - workstations
      example:
        terminalUuid: "c7a1b24b0583477292ebdbaa"
        pspId: "AGID_01"
        terminalId: "34523860"
        enabled: true
        payeeCode: "06534340721"
        workstations:
          - "cassa-1-ufficio-3"
          - "cassa-2-ufficio-3"

    Terminals:
      description: List of terminals
      type: object
      additionalProperties: false
      properties:
        terminals:
          type: array
          minItems: 0
          maxItems: 64
          items:
            $ref: '#/components/schemas/Terminal'
      required:
        - terminals
      example:
        terminals:
          - terminalUuid: "c7a1b24b0583477292ebdbaa"
            pspId: "AGID_01"
            terminalId: "34523860"
            enabled: true
            payeeCode: "06534340721"
          - terminalUuid: "635edc54ab35f303668bbe7e"
            pspId: "AGID_01"
            terminalId: "34523865"
            enabled: true
            payeeCode: "06534340721"

    TerminalsWithWorkstations:
      description: List of terminals
      type: object
      additionalProperties: false
      properties:
        terminals:
          type: array
          minItems: 0
          maxItems: 64
          items:
            $ref: '#/components/schemas/TerminalWithWorkstations'
      required:
        - terminals
      example:
        terminals:
          - terminalUuid: "c7a1b24b0583477292ebdbaa"
            pspId: "AGID_01"
            terminalId: "34523860"
            enabled: true
            payeeCode: "06534340721"
            workstations:
              - "cassa-1-ufficio-3"
              - "cassa-2-ufficio-3"
          - terminalUuid: "635edc54ab35f303668bbe7e"
            pspId: "AGID_01"
            terminalId: "34523865"
            enabled: true
            payeeCode: "06534340721"
            workstations:
              - "cassa-3-ufficio-3"
              - "cassa-4-ufficio-3"

    Transaction:
      description: Transaction details
      type: object
      additionalProperties: false
      properties:
        id:
          $ref: '#/components/schemas/TransactionId'
        pspId:
          $ref: '#/components/schemas/PspId'
        terminalId:
          $ref: '#/components/schemas/TerminalId'
        noticeNumber:
          $ref: '#/components/schemas/NoticeNumber'
        payeeCode:
          $ref: '#/components/schemas/PayeeCode'
        creationTimestamp:
          #description: Moment of creation of the transaction (ex. 2024-03-06T13:15:54Z, 2024-03-06T14:15:54+01:00)
          $ref: '#/components/schemas/Timestamp'
        lastUpdateTimestamp:
          #description: Moment of last update of the transaction (ex. 2024-03-06T13:15:54Z, 2024-03-06T14:15:54+01:00)
          $ref: '#/components/schemas/Timestamp'
        status:
          $ref: '#/components/schemas/Status'
        amount:
          #description: Payed amount
          $ref: '#/components/schemas/EuroCents'
      required:
        - id
        - pspId
        - terminalId
        - noticeNumber
        - payeeCode
        - creationTimestamp
        - lastUpdateTimestamp
        - status
      example:
        id: "4658fcb36e520a65b1be79d0"
        pspId: "AGID_01"
        terminalId: "34523860"
        noticeNumber: "485564829563528563"
        payeeCode: "06534340721"
        creationTimestamp: "2024-03-06T13:15:54Z"
        lastUpdateTimestamp: "2024-03-06T13:16:33Z"
        status: "CLOSED_OK"
        amount: 12345

    Transactions:
      description: List of transactions
      type: array
      minItems: 0
      maxItems: 128
      items:
        $ref: '#/components/schemas/Transaction'
      example:
        - id: "4658fcb36e520a65b1be79d0"
          pspId: "AGID_01"
          terminalId: "34523860"
          noticeNumber: "485564829563528563"
          payeeCode: "06534340721"
          creationTimestamp: "2024-03-06T13:15:54Z"
          lastUpdateTimestamp: "2024-03-06T13:16:33Z"
          status: "CLOSED_OK"
          amount: 12345

    UpdateTransaction:
      description: Request to update amount and status of a transaction
      type: object
      additionalProperties: false
      properties:
        status:
          $ref: '#/components/schemas/Status'
        amount:
          #description: Payed amount
          $ref: '#/components/schemas/EuroCents'
      required:
        - status
        - amount
      example:
        status: "CLOSED_OK"
        amount: 12345

    Workstations:
      description: List of cash desk labels
      type: object
      additionalProperties: false
      properties:
        workstations:
          $ref: '#/components/schemas/WorkstationsArray'
      required:
        - workstations
      example:
        workstations:
          - "cassa-1-ufficio-3"
          - "cassa-2-ufficio-3"

    WorkstationsArray:
      description: List of cash desk labels
      type: array
      minItems: 0
      maxItems: 32
      items:
        $ref: '#/components/schemas/Workstation'
      example:
        - "cassa-1-ufficio-3"
        - "cassa-2-ufficio-3"

  # ========================================================
  # Request bodies
  # ========================================================
  requestBodies:
    BulkLoadTerminals:
      description: Request to bulk load a set of terminals.
      content:
        multipart/form-data:
          schema:
            type: object
            properties:
              file:
                type: string
                format: binary
                maxLength: 134217728 # 256MB

    CreateOrUpdateTerminal:
      description: Request to create a new terminal or update an existing one
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/CreateOrUpdateTerminal'

    CreateTransaction:
      description: Request to create a transaction from Public Administration (payee) portal
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/CreateTransaction'

    UpdateTransaction:
      description: Request to update status and amount of a transaction
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/UpdateTransaction'

    UpdateWorkstations:
      description: Request to update cash desks linked to a terminal
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Workstations'

  # ========================================================
  # Parameters
  # ========================================================
  parameters:
    BulkLoadingId:
      name: bulkLoadingId
      in: path
      description: ID of a bulk loading operation
      required: true
      schema:
        $ref: '#/components/schemas/BulkLoadingId'
    
    EndDate:
      name: endDate
      in: query
      description: End date of the time range in which to search for transactions
      required: true
      schema:
        type: string
        format: date
        maxLength: 10
        example: "2022-11-30"

    PageNumber:
      name: page
      in: query
      description: Number of the requested page of data
      required: true
      schema:
        $ref: '#/components/schemas/PageNumber'

    PageSize:
      name: size
      in: query
      description: Size of the requested page of data
      required: true
      schema:
        $ref: '#/components/schemas/PageSize'

    PayeeCode:
      name: payeeCode
      in: query
      description: Fiscal code of the subject that receives the payment
      required: true
      schema:
        $ref: '#/components/schemas/PayeeCode'

    PspId:
      name: pspId
      in: query
      description: ID of the POS PSP
      required: true
      schema:
        $ref: '#/components/schemas/PayeeCode'

    RequestId:
      name: RequestId
      in: header
      description: Request Id that will be logged for troubleshooting purpose
      required: true
      schema:
        $ref: '#/components/schemas/UUID'

    SortStrategy:
      name: sortStrategy
      in: query
      required: true
      description: Strategy used to sort returned transactions by creation timestamp
      schema:
        type: string
        enum:
          - asc
          - desc
        example: "desc"

    StartDate:
      name: startDate
      in: query
      description: Start date of the time range in which to search for transactions
      required: true
      schema:
        type: string
        format: date
        maxLength: 10
        example: "2022-11-30"

    Status:
      name: status
      in: query
      description: Status of the transactions to search for
      required: true
      schema:
        $ref: '#/components/schemas/Status'
    
    TerminalId:
      name: terminalId
      in: query
      description: ID of the terminal for the PSP
      required: true
      schema:
        $ref: '#/components/schemas/TerminalId'
    
    TerminalUuid:
      name: terminalUuid
      in: path
      description: UUID of the terminal which is the target of the operation
      required: true
      schema:
        $ref: '#/components/schemas/TerminalUuid'

    TransactionId:
      name: transactionId
      in: path
      description: ID of the transaction target of the invoked operation
      required: true
      schema:
        $ref: '#/components/schemas/TransactionId'

    Workstation:
      name: workstation
      in: query
      description: Cash desk label
      required: true
      schema:
        $ref: '#/components/schemas/Workstation'

  # ========================================================
  # Responses
  # ========================================================
  responses:
    BulkLoadingReport:
      description: Report of a bulk loading operation
      headers:
        Access-Control-Allow-Origin:
          description: Indicates whether the response can be shared with requesting code from the given origin
          required: false
          schema:
            $ref: '#/components/schemas/AccessControlAllowOrigin'
        RateLimit-Limit:
          description: The number of allowed requests in the current period
          required: false
          schema:
            $ref: '#/components/schemas/RateLimitLimit'
        RateLimit-Reset:
          description: The number of seconds left in the current period
          required: false
          schema:
            $ref: '#/components/schemas/RateLimitReset'
      content:
        application/json:
          schema:
            type: string
            format: binary
            maxLength: 134217728 # 256MB

    BulkLoadTerminals:
      description: Response for bulk loading of terminals
      headers:
        Access-Control-Allow-Origin:
          description: Indicates whether the response can be shared with requesting code from the given origin
          required: false
          schema:
            $ref: '#/components/schemas/AccessControlAllowOrigin'
        RateLimit-Limit:
          description: The number of allowed requests in the current period
          required: false
          schema:
            $ref: '#/components/schemas/RateLimitLimit'
        RateLimit-Reset:
          description: The number of seconds left in the current period
          required: false
          schema:
            $ref: '#/components/schemas/RateLimitReset'
        Location:
          description: URL to get the status of bulk loading operation
          required: true
          schema:
            $ref: '#/components/schemas/BulkLoadingLocation'

    CreateTerminal:
      description: Response of create terminal operation
      headers:
        Access-Control-Allow-Origin:
          description: Indicates whether the response can be shared with requesting code from the given origin
          required: false
          schema:
            $ref: '#/components/schemas/AccessControlAllowOrigin'
        RateLimit-Limit:
          description: The number of allowed requests in the current period
          required: false
          schema:
            $ref: '#/components/schemas/RateLimitLimit'
        RateLimit-Reset:
          description: The number of seconds left in the current period
          required: false
          schema:
            $ref: '#/components/schemas/RateLimitReset'
        Location:
          description: URL of the terminal
          required: true
          schema:
            $ref: '#/components/schemas/TerminalLocation'

    CreateTransaction:
      description: Response to request to create a transaction from Public Administration (payee) portal
      headers:
        Access-Control-Allow-Origin:
          description: Indicates whether the response can be shared with requesting code from the given origin
          required: false
          schema:
            $ref: '#/components/schemas/AccessControlAllowOrigin'
        RateLimit-Limit:
          description: The number of allowed requests in the current period
          required: false
          schema:
            $ref: '#/components/schemas/RateLimitLimit'
        RateLimit-Reset:
          description: The number of seconds left in the current period
          required: false
          schema:
            $ref: '#/components/schemas/RateLimitReset'
        Location:
          description: URL of the transaction
          required: true
          schema:
            $ref: '#/components/schemas/TransactionLocation'

    Error:
      description: Error response
      headers:
        Access-Control-Allow-Origin:
          description: Indicates whether the response can be shared with requesting code from the given origin
          required: false
          schema:
            $ref: '#/components/schemas/AccessControlAllowOrigin'
        RateLimit-Limit:
          description: The number of allowed requests in the current period
          required: false
          schema:
            $ref: '#/components/schemas/RateLimitLimit'
        RateLimit-Reset:
          description: The number of seconds left in the current period
          required: false
          schema:
            $ref: '#/components/schemas/RateLimitReset'
        Retry-After:
          description: The number of seconds to wait before allowing a follow-up request
          required: false
          schema:
            $ref: '#/components/schemas/RetryAfter'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Errors'

    NoContent:
      description: No content response
      headers:
        Access-Control-Allow-Origin:
          description: Indicates whether the response can be shared with requesting code from the given origin
          required: false
          schema:
            $ref: '#/components/schemas/AccessControlAllowOrigin'
        RateLimit-Limit:
          description: The number of allowed requests in the current period
          required: false
          schema:
            $ref: '#/components/schemas/RateLimitLimit'
        RateLimit-Reset:
          description: The number of seconds left in the current period
          required: false
          schema:
            $ref: '#/components/schemas/RateLimitReset'
    
    PageOfTerminals:
      description: Page of terminals data
      headers:
        Access-Control-Allow-Origin:
          description: Indicates whether the response can be shared with requesting code from the given origin
          required: false
          schema:
            $ref: '#/components/schemas/AccessControlAllowOrigin'
        RateLimit-Limit:
          description: The number of allowed requests in the current period
          required: false
          schema:
            $ref: '#/components/schemas/RateLimitLimit'
        RateLimit-Reset:
          description: The number of seconds left in the current period
          required: false
          schema:
            $ref: '#/components/schemas/RateLimitReset'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/PageOfTerminals'

    PageOfTerminalsWithWorkstations:
      description: Page of terminals data
      headers:
        Access-Control-Allow-Origin:
          description: Indicates whether the response can be shared with requesting code from the given origin
          required: false
          schema:
            $ref: '#/components/schemas/AccessControlAllowOrigin'
        RateLimit-Limit:
          description: The number of allowed requests in the current period
          required: false
          schema:
            $ref: '#/components/schemas/RateLimitLimit'
        RateLimit-Reset:
          description: The number of seconds left in the current period
          required: false
          schema:
            $ref: '#/components/schemas/RateLimitReset'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/PageOfTerminalsWithWorkstations'

    PageOfTransactions:
      description: Page of retrieved transactions
      headers:
        Access-Control-Allow-Origin:
          description: Indicates whether the response can be shared with requesting code from the given origin
          required: false
          schema:
            $ref: '#/components/schemas/AccessControlAllowOrigin'
        RateLimit-Limit:
          description: The number of allowed requests in the current period
          required: false
          schema:
            $ref: '#/components/schemas/RateLimitLimit'
        RateLimit-Reset:
          description: The number of seconds left in the current period
          required: false
          schema:
            $ref: '#/components/schemas/RateLimitReset'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/PageOfTransactions'

    TerminalsWithWorkstations:
      description: Terminals list
      headers:
        Access-Control-Allow-Origin:
          description: Indicates whether the response can be shared with requesting code from the given origin
          required: false
          schema:
            $ref: '#/components/schemas/AccessControlAllowOrigin'
        RateLimit-Limit:
          description: The number of allowed requests in the current period
          required: false
          schema:
            $ref: '#/components/schemas/RateLimitLimit'
        RateLimit-Reset:
          description: The number of seconds left in the current period
          required: false
          schema:
            $ref: '#/components/schemas/RateLimitReset'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/TerminalsWithWorkstations'

    Transaction:
      description: Retrieved transaction
      headers:
        Access-Control-Allow-Origin:
          description: Indicates whether the response can be shared with requesting code from the given origin
          required: false
          schema:
            $ref: '#/components/schemas/AccessControlAllowOrigin'
        RateLimit-Limit:
          description: The number of allowed requests in the current period
          required: false
          schema:
            $ref: '#/components/schemas/RateLimitLimit'
        RateLimit-Reset:
          description: The number of seconds left in the current period
          required: false
          schema:
            $ref: '#/components/schemas/RateLimitReset'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Transaction'

  securitySchemes:
    bearerAuth:
      description: A bearer token in the format of a JWS and conforms to the specifications included in RFC8725
      type: http
      scheme: bearer
      bearerFormat: JWT